config/routes.rb
MyFirstApp::Application.routes.draw do

  root "static_pages#home"
  get "/about" => 'static_pages#about_us'
  get "/contact" => 'static_pages#contact_us'
  resources :products

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  before_save :downcase_name
  before_save :upcase_description

  def downcase_name
    self.name.downcase!
  end

  def upcase_description
     self.description.upcase!
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery except: [:create, :update], with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :product_find, only: [:show,:edit,:update,:destroy]
   
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

  def product_find
    @product=Product.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 
  def home
  end
  def about_us
  end
  def contact_us
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br/>
  <%= f.label :description %>
  <%= f.text_area :description %> <br/>
  <%= f.label :price %>
  <%= f.text_field :price %> <br/>
  <%= f.submit "Submit" %>

<% end %>

app/views/products/edit.html.erb
<h2> Edit Product </h2>
<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>  
<% end %>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>List of Products</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th><th></th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name, product_path(id: product.id) %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= link_to "edit", edit_product_path(product) %></td>
    <td><%= link_to "delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
<%end%>
</table>
<%= link_to "add", new_product_path %>

app/views/products/new.html.erb
<h2> Add a New Product </h2>

<% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>  
<% end %>
<%= render 'form' %>

app/views/products/show.html.erb
Name: <%= @product.name %> <br/>

Description: <%= @product.description %> <br/>

Price: <%= @product.price %> <br/>

<%= link_to "Back", products_path %>